### ISSUE TITLE
Odd code in rybu/examples/hator.txt  

### ISSUE THREAD

**Issue by StasKarpov** [zyla/rybu#10]
line 21-24 :
`  { put | count < BUFFER_SIZE } -> `
 `  { data[count] = 0; count = count + 1; return :ok; }`
` { put | count < BUFFER_SIZE } ->`
`   { data[count] = 1; count = count + 1; return :ok; } `

Does this mean something ?

**Comment by hator** [comment]
This code presents nondeterministic parameters. This is conceptually equivalent something like this:

  { put | count < BUFFER_SIZE } -> { data[count] = random(0,1); count = count + 1; return :ok; }

This means that verification will check both paths, with data[count] being set to either 0 and 1, and all of the future consequences -- if this action will happen three times then you will have all 8 possible combinations (000, 001, ..., 110, 111) checked.
