### ISSUE TITLE
Check for type errors in server initializers

### ISSUE THREAD

**Issue by zyla** [zyla/rybu#4]
Currently the following compiles:

    server foo { var val : 0..5 }
    var foo: foo() { val = :blah }

but generates incorrect Dedan code (nonexistent starting state `val_blah` for server `foo`).

Missing or redundant variables also aren't checked.

The variables are also required to be in alphabetical order, or nonexistent state is generated.

**Comment by hator** [comment]
Fixed in 0d23712c and c9c3639a.
